build: Build synopsis.c before main.c
synopsis.c was defined as dependency of the nbdkit program, but it
should be define as dependency of main.c. Otherwise "make" fail with:

main.c:180:10: fatal error: synopsis.c: No such file or directory
 #include "synopsis.c"
          ^~~~~~~~~~~~

Fixes commit 445e18f3dbb2 (src, docs: Generate the nbdkit command
synopsis from a single source).